### ISSUE TITLE
I just open an issue to say thank you

### ISSUE THREAD

**Issue by AmibeSkyfy16** [Peanuuutz/tomlkt#17]
I had to do a lot of research and I couldn't find what I wanted, but I came across your project and the fact that you can add comments to fields in a data class is great, I didn't find that anywhere else ! This is my project that use your code https://github.com/AmibeSkyfy16/BypassAnvilRestriction/tree/master/src/main/kotlin/ch/skyfy/bypassanvilrestriction/config
https://github.com/AmibeSkyfy16/TomlConfigLib
![sample](https://user-images.githubusercontent.com/85696108/185300469-b3db726c-d5ed-4389-8282-de77a18fa5ce.png)

**Comment by Peanuuutz** [comment]
I'm **so** glad that you have a good time with it 😸. I see you are using interface to extend funtionality, I hope that polymorphism limitation isn't so destructive because nowadays I've spent my time into another project (which is minecraft related) and won't finish in a short time 🤔.
> [Guess what](https://github.com/Peanuuutz/intelli-bow/blob/dev/src/main/kotlin/net/peanuuutz/intellibow/config/IBConfig.kt)

**Comment by AmibeSkyfy16** [comment]
👍
