### ISSUE TITLE
Allow users to provide DateTime deserializer

### ISSUE THREAD

**Issue by Wavesonics** [Peanuuutz/tomlkt#31]
I'm trying to move to this library instead of another, but one sticking point is that I have DateTime objects throughout my serialized data, so currently it just throws when it encounters a bare date time string:
```
net.peanuuutz.tomlkt.internal.UnexpectedTokenException: '-' (L2)
	at net.peanuuutz.tomlkt.internal.parser.TomlFileParser.unexpectedToken(TomlFileParser.kt:96)
	at net.peanuuutz.tomlkt.internal.parser.TomlFileParser.unexpectedIf(TomlFileParser.kt:104)
	at net.peanuuutz.tomlkt.internal.parser.TomlFileParser.parseNumberValue(TomlFileParser.kt:453)
	at net.peanuuutz.tomlkt.internal.parser.TomlFileParser.parseValue(TomlFileParser.kt:300)
	at net.peanuuutz.tomlkt.internal.parser.TomlFileParser.parse(TomlFileParser.kt:141)
```

on data:
```toml
[info]
	created = 2023-08-23T03:28:54.933599600Z
```

I understand the problem you're encountering, but it seems worth trying to solve in my opinion.

On the parsing side, I _think_ that is already solved:
`Instant.parse(dateStr).toLocalDateTime(TimeZone.UTC)`

Maybe one option for formatting for now could be delegating to another library such as **Klock**:
https://docs.korge.org/klock/format/#iso8601-serialization-and-parsing

It looks like TOML, Kotlin's `Instant.parse`, and Klock, all support parsing/formatting of the proper spec:
ISO 8601
[RFC 3339](https://tools.ietf.org/html/rfc3339)

But either way, if none of these solutions are acceptable for the library it's self, being able to allow users to provide their own deserializers for the type would at least unblock people who need this data type.

**Comment by Peanuuutz** [comment]
Good news for you. We're working on it recently. We plan to support it on JVM without kotlinx.datetime by default. For other platforms, kotlinx.datetime is a `compileOnly` dependency, which could be added on demand.

**Comment by Wavesonics** [comment]
oh thats great news, so by adding `kotlinx.datetime` for say, iOS, it would "just work"?

**Comment by Peanuuutz** [comment]
> oh thats great news, so by adding `kotlinx.datetime` for say, iOS, it would "just work"?

I just noticed that `compileOnly` is not avaliable for native targets, so I changed kotlinx.datetime as `api` dependency. JVM remains untouched (use java.time, not kotlinx.datetime, so no extra dependency 😉).

**Comment by Wavesonics** [comment]
is there a mechanism to provide custom serializes for other types?

**Comment by Peanuuutz** [comment]
0.3.0 has just released. Please check the release note and the new README for detail.

**Comment by Wavesonics** [comment]
It works!
