### ISSUE TITLE
Add a configurable "lienent mode"

### ISSUE THREAD

**Issue by Wavesonics** [Peanuuutz/tomlkt#32]
It would be nice if we could configure the deserializer to be more lenient, such that if a field is missing from the serialized form, and is nullable in the data class, it just assigns `null`.

```kotlin
@Serializable
data class Info(
	val created: String,
	val lastAccessed: String?,
)
```

And I try to decode:
```toml
created="now"
```
It will just assign `null` to `lastAccessed`

**Comment by Peanuuutz** [comment]
I think this is already handled in auto-generated serializers. Just add `null` as default value to `lastAccessed`. 👀

**Comment by Wavesonics** [comment]
oh yup, that works!
