### ISSUE TITLE
@TomlMultilineString adding a `\n` to the start of the string

### ISSUE THREAD

**Issue by Wavesonics** [Peanuuutz/tomlkt#37]
If I take a bare string such as `"foo"` and run it through a serialize/deserialize cycle in a field marked with `@TomlMultilineString` it will come back out the other side as `"\nfoo"`

Maybe as simple as trimming the input after parsing on Multiline strings? not sure.

**Comment by Peanuuutz** [comment]
Forgot to handle the initial line feed.

**Comment by Wavesonics** [comment]
Fantastic! I just moved my project over to tomlkt and it seems to be working great! This line feed issue will solve the only problem I've come across so far.

**Comment by Peanuuutz** [comment]
Good job! 😄 Actually I'm improving unit test in the meantime and oh boy already found some hidden bugs. 😅

**Comment by Wavesonics** [comment]
Glad to hear it! My project just cross the 20% code cov barrier so... I get it 😁

**Comment by Peanuuutz** [comment]
0.3.1 released. Please check if it works properly.

**Comment by Wavesonics** [comment]
It's fixed!
