### ISSUE TITLE
add linux_arm64 supports

### ISSUE THREAD

**Issue by selcarpa** [Peanuuutz/tomlkt#56]
is there a plan to add linux_arm64 supports

**Comment by Peanuuutz** [comment]
Next y version.

**Comment by Peanuuutz** [comment]
Blocked by https://github.com/Kotlin/kotlinx-datetime/issues/300.

**Comment by Peanuuutz** [comment]
#57

**Comment by Peanuuutz** [comment]
0.3.6 arrives with linuxArm64 support. Please check out [release note](https://github.com/Peanuuutz/tomlkt/releases/tag/v0.3.6) for more information.
