### ISSUE TITLE
Update multiplatform targets

### ISSUE THREAD

**Issue by Wavesonics** [Peanuuutz/tomlkt#63]
The latest KMP update changed up their targets a bit, specifically their iOS targets.

`ios()` was deprecated:
```
'ios(Action<KotlinNativeTarget>): Unit' is deprecated. Use applyDefaultHierarchyTemplate() instead. Deprecated since 1.9.20, scheduled for removal in 2.0
```

**Comment by Peanuuutz** [comment]
> Would it be possible to get a `0.3.8` published? Looks like the work is done but still unavailable for consumers.

We're waiting for Kotlin 2.0 release so can jump to 0.4.0 directly.

**Comment by Wavesonics** [comment]
Kotlin 2.0 is out! 💥🥳🍾
