### ISSUE TITLE
Add kotlinx-datetime 0.6.0 compatible support

### ISSUE THREAD

**Issue by selcarpa** [Peanuuutz/tomlkt#66]
Please add kotlinx-datetime 0.6.0 compatible support, when I use kotlinx-datetime 0.6.0 and tomlkt at the same time, native packaging cannot be done.

[https://github.com/Kotlin/kotlinx-datetime/issues/397#issuecomment-2126036559](https://github.com/Kotlin/kotlinx-datetime/issues/397#issuecomment-2126036559)

**Comment by Peanuuutz** [comment]
Fixed in 0.4.0.
